#! /usr/bin/env ruby

# Don't try to add more than this many untracked files.
# (In case a large directory shows up as untracked.)
MAX_UNTRACKED = 8

file_args = ARGV.reject { |arg| arg.start_with?('-') }

status_lines = `git status -u --porcelain #{file_args.join(' ')}`.lines(chomp: true)
untracked = status_lines.filter_map do |line|
  next unless line.start_with? '??'

  path = line[3..]
  if `wc -l #{path}`.to_i > 300
    puts "Skipping long file #{path}. You can add it with `git add #{path}`\n"
  else
    path
  end
end

if untracked.count > MAX_UNTRACKED
  puts "Not adding #{untracked.count} untracked files.\nYou can add them with `git add -A`\n"
  untracked = []
elsif untracked.any?
  system "git add -N #{untracked.join(' ')}"
end

begin
  system "git add -p #{ARGV.join(' ')}"
rescue Interrupt => e
  puts "\n"
end

if untracked
  status = `git status -u --porcelain #{file_args.join(' ')}`
  status.each_line(chomp: true) do |line|
    if line.start_with?(' A ') && untracked.include?(path = line[3..])
      system "git restore --staged #{path}"
    end
  end
end

exec 'git status'
