#! /usr/bin/env RBENV_VERSION=2.7.8 ruby

require 'rubygems'
require 'active_support'
require 'active_support/core_ext'
require 'readline'

if ARGV.blank?
  raise "Usage: git timewarp 2 days ago"
end

begin
  date = eval ARGV.join(' ')
rescue SyntaxError
  date = eval ARGV.join('.')
end

raise "#{date.inspect} is not a time" unless date.is_a? Time

puts command = %(env GIT_AUTHOR_DATE="#{date.inspect}" GIT_COMMITTER_DATE="#{date.inspect}" git commit)

commit_message = Readline.readline("Enter commit message (q to cancel): ", true)

if commit_message.length > 4
  command += " -m \"#{commit_message}\""
  exec command
elsif commit_message.empty?
  exec command
end
